services:
  purrbalancer:
    build:
      context: ./PurrBalancer  # Adjust this path based on your repo structure
      dockerfile: Dockerfile
    container_name: purrbalancer
    ports:
      - "8080:8080"
    environment:
      - HOST=+
      - PORT=8080
      - SECRET=ashes
    networks:
      - purrnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  purrlay:
    build:
      context: ./PurrLay  # Adjust this path based on your repo structure
      dockerfile: Dockerfile
    container_name: purrlay
    ports:
      - "8081:8081"    # HTTP API
      - "6942:6942"    # WebSockets
      - "7777:7777"    # UDP
    environment:
      - HOST=+
      - PORT=8081
      - SECRET=ashes
      - BALANCER_URL=http://localhost:8080
      - HOST_SSL=false
      - HOST_REGION=us-west
      - HOST_DOMAIN=displaced.ddns.net
      - HOST_PORT=8081
    networks:
      - purrnet
    depends_on:
      - purrbalancer
    restart: unless-stopped

networks:
  purrnet:
    driver: bridge

