# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy backend and frontend folders
COPY . .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .

ENV HOST=+
ENV PORT=80

EXPOSE ${PORT}

ENTRYPOINT ["dotnet", "PurrBalancer.dll"]
