namespace PurrLay;

public enum SERVER_PACKET_TYPE : byte
{
    SERVER_CLIENT_CONNECTED = 0,
    SERVER_CLIENT_DISCONNECTED = 1,
    SERVER_CLIENT_DATA = 2,
    SERVER_AUTHENTICATED = 3,
    SERVER_AUTHENTICATION_FAILED = 4
}
